"""empty message

Revision ID: 4bda0fe8e5dd
Revises: 
Create Date: 2018-10-08 22:24:16.842847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bda0fe8e5dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('activity_type', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_comment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('community_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_member',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('uid1', sa.String(), nullable=True),
    sa.Column('uid2', sa.String(), nullable=True),
    sa.Column('action_user', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_post',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('image', sa.Boolean(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('hatsoffs', sa.Integer(), nullable=True),
    sa.Column('public_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community_post')
    op.drop_table('community_member')
    op.drop_table('community_comment')
    op.drop_table('activity')
    # ### end Alembic commands ###
